format:
  picture_size: [400, 400]
  order_picture_size: "120x120"
  number_delimiter: ","
  product_picture_size: "100x85"
admin:
  categories_list:
    per_page: 10
  users_list:
    per_page: 10
  orders_list:
    per_page: 15
  product_list:
    per_page: 10
  requests_list:
    per_page: 15
home:
  display_product: 8
hot_trend: 15
max_item_for_recent: 10
user:
  avatar_size: 70
user:
  orders_history:
    per_page: 10
  requests:
    per_page: 10
  login:
    app_id: "404823109860244"
    app_secrete: "2a978a6fc2f9234cfb76d5cf5b596146"
email:
  name: "Your Gmail account name"
  password: "Your gmail password"
  from: "Your from email system"
category:
  display_product:
    per_page: 12
chart:
  weeks: 4
