format:
  picture_size: [400, 400]
  order_picture_size: "120x120"
admin:
  users_list:
    per_page: 10
  orders_list:
    per_page: 15
  product_list:
    per_page: 10
  requests_list:
    per_page: 15
home:
  display_product: 8
hot_trend: 15
max_item_for_recent: 10
user:
  avatar_size: 70
user:
  requests:
    per_page: 10
  login:
    app_id: "404823109860244"
    app_secrete: "2a978a6fc2f9234cfb76d5cf5b596146"
