format:
  picture_size: [400, 400]
admin:
  users_list:
    per_page: 10
  orders_list:
    per_page: 15
  product_list:
    per_page: 10
home:
  display_product: 8
hot_trend: 15
max_item_for_recent: 10
user:
  avatar_size: 70
